#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# Created: Sun  9 Jun 2019 23:45:18 IST
# Last-Updated: Mon 10 Jun 2019 01:41:17 IST
#
# lsg is part of dotfiles
# URL: https://gitlab.com/justinekizhak/dotfiles
# Description: Check if a specific file or folder exists in current or in a
# specified directory.
# This script started as an alias to `ls | grep FILENAME` but now its more
# flexible and robust than that.
# Usage: `lsg FILENAME -p PATH_TO_SEARCH [flags -c]`
#
# Copyright (c) 2019, Justine Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.
#
# -----------------------------------------------------------------------------

import os
import argparse


def search(search_path, search_term):
    result = {'files': [], 'directories': [], 'links': []}
    for entry in os.listdir(search_path):
        if search_term.lower() in entry.lower():
            if os.path.isdir(os.path.join(search_path, entry)):
                result['directories'].append(entry)
            if os.path.isfile(os.path.join(search_path, entry)):
                result['files'].append(entry)
    return result


def print_result(result):
    number_of_directories = len(result['directories'])
    number_of_files = len(result['files'])
    number_of_links = len(result['links'])

    # print directories
    if (number_of_directories > 0):
        print(number_of_directories,
              "Directories-------------------------------->")
        for directory in result['directories']:
            print(directory)

    #print files
    if (number_of_files > 0):
        print(number_of_files, "Files-------------------------------------->")
        for f in result['files']:
            print(f)

    #print links
    if (number_of_links > 0):
        print(number_of_links, "Links-------------------------------------->")
        for l in result['links']:
            print(l)


if __name__ == "__main__":
    """The main routine."""
    parser = argparse.ArgumentParser(
        description='Check if a specific file or folder \
    exists in current or in a specified directory')
    parser.add_argument('file name',
                        metavar='FILENAME',
                        type=str,
                        nargs='+',
                        help='name of file or folder to search')
    parser.add_argument('--path', '-p',
                        metavar='PATH',
                        dest='path',
                        default=".",
                        help='path to search (default: current directory)')
    args = parser.parse_args()
    search_term = args.search_term[0]
    search_path = os.getcwd() + "/" + args.path
    result = search(search_path, search_term)
    print_result(result)
