#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------


echo
"Behaviour: Will delete any existing python build files.
Create package from scratch"

read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Deleting build folders..."
    rm -rf build dist devinstaller.egg-info/
    echo "Done. Creating packages..."
    python3 setup.py sdist bdist_wheel
    echo "All done."
fi
