#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------
# Install pip packages in new virtualenv.

python3 -m venv ~/python-virtualenvs/"$1"
~/python-virtualenvs/"$1"/bin/pip install "$1"
